#!/bin/bash
set -e
#set -x

FULLSCRIPT=$(which $0)
BIN_PATH=`dirname ${FULLSCRIPT}`
TARGET_PATH=${BIN_PATH}/../target/Playnomics
VERSION_NUM=$1

if [[ -z "$1" ]]; then
    echo "Version number is not set!"
    exit 1
fi


XCODE5="/Applications/Xcode5.app/Contents/Developer/usr/bin/xcodebuild"

SRC_PATH=${BIN_PATH}/../src

FILE_NAME="libPlaynomicsSDK.a"
FINAL_FILE_NAME=${TARGET_PATH}/libPlaynomics.a

SYMROOT="build"

RELEASE_DEVICE_ARMV7_DIR=build/Release-iphoneos-armv7
RELEASE_SIMULATOR_DIR=build/Release-iphonesimulator
RELEASE_DEVICE_ARM64_DIR=build/Release-iphoneos-arm64

SIMULATOR=iphonesimulator7.0

LOG_PATH=${BIN_PATH}/build.log

if [ -d "$TARGET_PATH" ]; then
    echo "Cleaning out old target directory"
    rm -r ${TARGET_PATH}
fi
mkdir ${TARGET_PATH}

echo "Starting build for iOS SDK. Log file for xcodebuild is ${LOG_PATH}"

echo "Building for arm7, arm7s"
xcodebuild -project PlaynomicsSDK.xcodeproj -configuration 'Release' -sdk 'iphoneos7.0' clean build ARCHS='armv7 armv7s' IPHONEOS_DEPLOYMENT_TARGET='5.0' TARGET_BUILD_DIR='./build-arm' BUILT_PRODUCTS_DIR='./build-arm' >> ${LOG_PATH}
echo "Building for i386"
xcodebuild -project PlaynomicsSDK.xcodeproj -configuration 'Release' -sdk 'iphonesimulator7.0' clean build ARCHS='i386' IPHONEOS_DEPLOYMENT_TARGET='5.0' TARGET_BUILD_DIR='./build-i386' BUILT_PRODUCTS_DIR='./build-i386' >> ${LOG_PATH}
echo "Building for arm64"
xcodebuild -project PlaynomicsSDK.xcodeproj -configuration 'Release' -sdk 'iphoneos7.0' clean build ARCHS='arm64' IPHONEOS_DEPLOYMENT_TARGET='7.0' TARGET_BUILD_DIR='./build-arm64' BUILT_PRODUCTS_DIR='./build-arm64' >> ${LOG_PATH}

echo "Merging build libraries into ${FINAL_FILE_NAME}"

lipo -create -output "${FINAL_FILE_NAME}" "./build-arm/${FILE_NAME}" "./build-i386/${FILE_NAME}" "./build-arm64/${FILE_NAME}"

cp PlaynomicsSDK/Playnomics.h ${TARGET_PATH}
cp PlaynomicsSDK/PNLogger.h ${TARGET_PATH}

echo "Compressing build into file ${TARGET_PATH}/../playnomics_ios_sdk_v${VERSION_NUM}.tar.gz"

cd ${TARGET_PATH}/../
tar -zcf playnomics_ios_sdk_v${VERSION_NUM}.tar.gz Playnomics
